repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [
          "--fix",
          "--unsafe-fixes"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-n', '4']  # 並列数をここで指定、今は4で。
        files: ^(src/|main\.py)
        exclude: ^src/tests/

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: zsh -c -c 'PYTHONPATH=src .venv/bin/pytest src/tests/regression'
        language: system
        pass_filenames: false
        always_run: true